services:
  - type: web
    name: Stenzle 
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: API_HASH
        sync: false
      - key: API_ID
        sync: false
      - key: SESSION
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: SUPPORT_CHAT
        sync: false
      



